import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { formatNaira } from "./format";

export type PdfDocInput = {
  docType: "INVOICE" | "PURCHASE ORDER";
  docNumber: string;
  date: string;
  dueDate?: string | null;
  status?: string;
  business: { name: string; currency?: string };
  partyLabel: string; // "Bill to" or "Supplier"
  party: { name: string; phone?: string | null; email?: string | null; address?: string | null };
  items: { description: string; quantity: number; unit_price: number; line_total: number }[];
  subtotal: number;
  tax?: number;
  total: number;
  notes?: string | null;
};

export function buildPdf(input: PdfDocInput) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const M = 40;

  // Header
  doc.setFont("helvetica", "bold").setFontSize(22);
  doc.text(input.docType, M, 56);
  doc.setFont("helvetica", "normal").setFontSize(10);
  doc.text(`#${input.docNumber}`, M, 74);
  if (input.status) {
    doc.setFont("helvetica", "bold");
    doc.text(input.status.toUpperCase(), pageW - M, 56, { align: "right" });
    doc.setFont("helvetica", "normal");
  }

  // Business
  doc.setFontSize(11).setFont("helvetica", "bold");
  doc.text(input.business.name, pageW - M, 74, { align: "right" });
  doc.setFont("helvetica", "normal").setFontSize(9);
  doc.text(`Date: ${input.date}`, pageW - M, 90, { align: "right" });
  if (input.dueDate) doc.text(`Due: ${input.dueDate}`, pageW - M, 104, { align: "right" });

  // Party block
  doc.setFontSize(10).setFont("helvetica", "bold");
  doc.text(input.partyLabel, M, 120);
  doc.setFont("helvetica", "normal");
  let py = 134;
  doc.text(input.party.name, M, py); py += 14;
  if (input.party.phone) { doc.text(input.party.phone, M, py); py += 14; }
  if (input.party.email) { doc.text(input.party.email, M, py); py += 14; }
  if (input.party.address) { doc.text(String(input.party.address).slice(0, 80), M, py); py += 14; }

  // Items table
  autoTable(doc, {
    startY: Math.max(py + 8, 180),
    head: [["Description", "Qty", "Unit price", "Total"]],
    body: input.items.map((it) => [
      it.description,
      String(it.quantity),
      formatNaira(it.unit_price),
      formatNaira(it.line_total),
    ]),
    styles: { fontSize: 10, cellPadding: 6 },
    headStyles: { fillColor: [30, 41, 59], textColor: 255 },
    columnStyles: { 1: { halign: "right" }, 2: { halign: "right" }, 3: { halign: "right" } },
    margin: { left: M, right: M },
  });

  // Totals
  // @ts-expect-error autoTable adds lastAutoTable
  const endY: number = doc.lastAutoTable.finalY + 16;
  const lx = pageW - M - 180;
  const vx = pageW - M;
  doc.setFontSize(10);
  doc.text("Subtotal", lx, endY);
  doc.text(formatNaira(input.subtotal), vx, endY, { align: "right" });
  if (input.tax) {
    doc.text("Tax", lx, endY + 16);
    doc.text(formatNaira(input.tax), vx, endY + 16, { align: "right" });
  }
  doc.setFont("helvetica", "bold").setFontSize(12);
  const ty = endY + (input.tax ? 38 : 22);
  doc.text("Total", lx, ty);
  doc.text(formatNaira(input.total), vx, ty, { align: "right" });

  if (input.notes) {
    doc.setFont("helvetica", "normal").setFontSize(9);
    doc.text("Notes:", M, ty + 28);
    doc.text(doc.splitTextToSize(input.notes, pageW - M * 2) as string[], M, ty + 42);
  }

  doc.setFontSize(8).setTextColor(120);
  doc.text("Generated by iTrova", M, doc.internal.pageSize.getHeight() - 24);

  return doc;
}

export function downloadPdf(input: PdfDocInput, filename: string) {
  buildPdf(input).save(filename);
}
